### ISSUE TITLE
Import from old Downloads Module

### ISSUE THREAD

**Issue by FRWo** [Portugao/MUFiles#24] opened 2015-04-22 06:30 UTC
It would be great if you could make an import routine for the old Downloads Module

So we have to do:

- [x] implement controller
- [x] implement api, that creates a collection for each category
- [x] implement api, that creates the entries for each item of downloads; we have to work with the correct upload directory in downloads
- [x] fine tuning, delete id in tiltle of collections, create placeholder collection for files without collection because of missing category in downloads module
- [x] some categories get no entry in workflow table
- [x] fix charset issue in title of collections
- [x] fix copy of files into MUFiles folder does not work
- [x] fix some files does not get imported
- [x] fix the fact that some collections have a sub collection with a higher id
- [ ] fix files not in workflow table
- [ ] fix the collection does not get renamed ( without old id)
- [ ] fix no meta datas

**Comment by Portugao** [comment] 2015-04-22 15:27
For that it would be great, like said in the german forum, to have your actual tables and files of the download module....

**Comment by Portugao** [comment] 2015-04-24 08:47
Thx for your datas. Seems some categories have a parent category that is not there anymore.

**Comment by Portugao** [comment] 2015-04-30 19:27
@FRWo 
One question:
In the downloads module a category has a column 'pn_cid' and 'pn_pid'.
Does it mean that a category can have a parent category?

**Comment by FRWo** [comment] 2015-05-01 17:46
yes, indeed. There are a plenty categories with a parent category. but the handling of categories was inside the dowload module.


Michael Ueberschaer schrieb am 30.04.2015 21:27:

**Comment by Portugao** [comment] 2015-05-01 18:28
Ok. So the categories in the downloads module get collections in MUFiles.

**Comment by Portugao** [comment] 2015-06-08 12:24
@FRWo 
Would be fine if you could have a look on the import function is implemented now. There should only be an issue with the tiltles and the charset.....
Please use the link 'Download Zip'!

**Comment by Portugao** [comment] 2015-06-08 12:27
The prefix should be deleted...

**Comment by FRWo** [comment] 2015-06-08 16:26
Thanks, I will try soon…

Hav I to delete the prefix before doing the import?

 

Von: Michael Ueberschaer [mailto:notifications@github.com] 
Gesendet: Montag, 8. Juni 2015 14:28
An: Portugao/MUFiles
Cc: Frank
Betreff: Re: [MUFiles] Import from old Downloads Module (#24)

 

The prefix should be deleted...

**Comment by Portugao** [comment] 2015-06-08 16:53
Yes.

**Comment by FRWo** [comment] 2015-06-09 06:06
Hi Michael,

 

1.0.1.        tested import from old Downloads – Modul:

Removed the prefix with phpmyadmin

copying the files over 1.00 modul

Install it

Click on import

è DONE

 

Great work – Thanks!

 

Von: Michael Ueberschaer [mailto:notifications@github.com] 
Gesendet: Montag, 8. Juni 2015 18:53
An: Portugao/MUFiles
Cc: Frank
Betreff: Re: [MUFiles] Import from old Downloads Module (#24)

 

Yes.

**Comment by Portugao** [comment] 2015-06-09 07:58
Fine!
Do you have any problems with the charset in titles of collections?

**Comment by FRWo** [comment] 2015-06-09 08:45
Yes, but this is a minor, I can do this by hand (see att.)

 

Von: Michael Ueberschaer [mailto:notifications@github.com] 
Gesendet: Dienstag, 9. Juni 2015 09:59
An: Portugao/MUFiles
Cc: Frank
Betreff: Re: [MUFiles] Import from old Downloads Module (#24)

 

Fine!
Do you have any problems with the charset in titles of collections?

**Comment by Portugao** [comment] 2015-06-09 08:50
Ok. So i close this issue.

**Comment by FRWo** [comment] 2015-06-09 08:53
There seems to be a problem with the categories, because I cannot do a filter with subcategories.

The categories are show, but I get only “Keine Kollektionen gefunden”, so the only way to see any collections is filter with “all”

**Comment by Portugao** [comment] 2015-06-09 09:49
Yes. I think, it was or is an issue of ModuleStudio.
Make a new issue for that, so it will not get lost. Will be fixed with new generated code I hope.

**Comment by FRWo** [comment] 2015-06-09 11:21
https://github.com/Guite/MostGenerator/issues/682

**Comment by Portugao** [comment] 2015-06-14 10:24
@FRWo 
About filter with subcategories..
I cannot reproduce. Maybe i misunderstood your point.

**Comment by FRWo** [comment] 2015-06-15 06:48
The problem is:

after doing the import I have a listfield "Kategorien" with the Categories from the core (not the parent-categories from the old download modul) and another field "Kollektionen" with all the categories (parent and sub) from the old modul.
Most filters from "Kollektion" will result in "Keine Kollektionen gefunden".
How could I filter (as before in Download modul) -> Parent Category -> Subcategory -> Show results...?

F.E.: Allgemeines -> Vordrucke -> schould be 11 entries. Filtering: "Kollektionen" = Allgemeines, after that "Kollektionen" = Vordrucke (count=11), result: "Keine Kollektionen gefunden"

**Comment by Portugao** [comment] 2015-06-15 09:19
About which template do we speak?
View of collections or of files?

**Comment by Portugao** [comment] 2015-06-15 09:27
Ah. I see. About view of collections.
```
Which result do you expect with
-> Parent Category -> Subcategory -> Show results...?
What should be the result?
```
The filter is looking for collections with the selected collection as parent collection.

**Comment by FRWo** [comment] 2015-06-15 09:35
The result I wish to see is only the files that are part of this specific subcategory.

My user often click of Parentgategory to see, what subcategories are available and than see what files are available in this subcat.
(Instead of doing a search....)

Michael Ueberschaer schrieb am 15.06.2015 11:27:

**Comment by Portugao** [comment] 2015-06-15 09:41
To see which files are available one can call the display of a collection.

**Comment by FRWo** [comment] 2015-06-15 10:31
OK, I see.

Is it possible to view only the parent-categories in the first listfied to choose from collections?

And for that, I think we could close this issue - step by step I understand what the module could be used for...
Many thanks for the work and the patience

Michael Ueberschaer schrieb am 15.06.2015 11:41:

**Comment by Portugao** [comment] 2015-06-15 10:40
```
Is it possible to view only the parent-categories in the first listfied to choose from collections?
```
For that you could open a new issue to speak about....this issue is closed.

**Comment by Portugao** [comment] 2016-07-25 14:29
@FRWo 
Reopened this.

**Closed** 2016-08-20 15:01 UTC
Labels: backend, features

**Comment by Portugao** [comment] 2016-08-20 15:02
@FRWo 
The import should work now; please give it another try.

**Comment by FRWo** [comment] 2016-08-20 15:49
I do,  directly after a week off…

 

Von: Michael Ueberschaer [mailto:notifications@github.com] 
Gesendet: Samstag, 20. August 2016 17:02
An: Portugao/MUFiles
Cc: Frank; Mention
Betreff: Re: [Portugao/MUFiles] Import from old Downloads Module (#24)

 

@FRWo <https://github.com/FRWo>  
The import should work now; please give it another try.

**Comment by FRWo** [comment] 2016-08-29 06:36
Just tested - works fine for me, thank you 
+1

**Comment by Portugao** [comment] 2016-08-29 06:45
That's fine.
